version: "3"
services:
  artemis:
    image: romanowalex/artemis:2.19.0
    container_name: artemis
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "8161:8161"
      - "61616:61616"
    healthcheck:
      test: [ "CMD-SHELL", "/opt/activemq-artemis/bin/artemis check queue --name TEST --consume 10 --url tcp://localhost:61616 --user $$ARTEMIS_USER --password $$ARTEMIS_PASSWORD" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - artemis:/app/artemis/brokers

volumes:
  artemis:
