spring:
  application:
    name: jpa-example
  profiles:
    active: local
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/jms
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jms:
    listener:
      acknowledge-mode: auto
      concurrency: 1
      max-concurrency: 1
    pub-sub-domain: false
    template:
      qos-enabled: true
      priority: 100
      receive-timeout: 1000
      time-to-live: 36000
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

application:
  artemis:
    username: ${ARTEMIS_USERNAME:test}
    password: ${ARTEMIS_PASSWORD:test}
    broker-url: ${ARTEMIS_BROKER_URL:amqp://localhost:61616}
logging:
  level:
    org.apache.qpid: debug
    org.springframework.jms: debug
