spring:
  application:
    name: jpa-example
  profiles:
    active: local
  main.banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/jms
    username: program
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: false

application:
  artemis:
    username: ${ARTEMIS_USERNAME:test}
    password: ${ARTEMIS_PASSWORD:test}
    broker-url: ${ARTEMIS_BROKER_URL:amqp://localhost:61616}
logging:
  level:
    org.apache.qpid: debug
    org.springframework.jms: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
